import type { Metadata } from "next";
import { Glory, Work_Sans } from "next/font/google";
import "./globals.css";

const glory = Glory({
  variable: "--font-glory",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${glory.variable} ${workSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
